'use strict';

// Resources: the two memory layers, CPU, and the panel-enforced disk quota.

import type { Field } from './types';

const fields: Field[] = [
  {
    key: 'MEMORY',
    scope: 'env',
    label: 'RAM (Java heap)',
    help: 'Memory the Minecraft/Java process may use. The image passes this to the JVM as both initial and max heap. Modpacks usually need 4 GB or more; the image default of 1 GB is only enough for small vanilla servers.',
    type: 'size-mb',
    unit: 'MB',
    default: 1024,
    min: 512,
    max: 65536,
    step: 512,
    mode: 'simple',
    section: 'resources',
    requiresRestart: true,
  },
  {
    key: 'INIT_MEMORY',
    scope: 'env',
    label: 'Initial heap (advanced)',
    help: 'Sets a different starting heap than the maximum. Leave empty to let "RAM (Java heap)" control both. Only useful when you want the JVM to grow into its memory gradually.',
    type: 'size-mb',
    unit: 'MB',
    mode: 'advanced',
    section: 'resources',
    requiresRestart: true,
  },
  {
    key: 'MAX_MEMORY',
    scope: 'env',
    label: 'Maximum heap (advanced)',
    help: 'Sets a different maximum heap than the initial one. Leave empty to let "RAM (Java heap)" control both.',
    type: 'size-mb',
    unit: 'MB',
    mode: 'advanced',
    section: 'resources',
    requiresRestart: true,
  },
  {
    key: 'memory',
    scope: 'docker',
    label: 'Container memory limit',
    help: 'Hard cap enforced by Docker on the whole container (HostConfig.Memory). Keep it 25–50% above the Java heap: Java needs off-heap room, and hitting this cap kills the server process instantly (OOM kill).',
    type: 'size-mb',
    unit: 'MB',
    default: 6144,
    min: 1024,
    max: 262144,
    step: 512,
    mode: 'simple',
    section: 'resources',
    requiresRestart: true,
  },
  {
    key: 'memorySwap',
    scope: 'docker',
    label: 'Container swap limit',
    help: 'Extra swap space the container may use beyond its memory limit. 0 disables swap. Swapping a Minecraft server causes heavy lag — leave at 0 unless you know you need it.',
    type: 'size-mb',
    unit: 'MB',
    default: 0,
    min: 0,
    max: 65536,
    step: 512,
    mode: 'advanced',
    section: 'resources',
    requiresRestart: true,
  },
  {
    key: 'cpus',
    scope: 'docker',
    label: 'CPU limit',
    help: 'How many host CPU cores the server may use (Docker NanoCpus). 0 means unlimited. When a server hits its cap it slows down (tick lag) rather than being killed.',
    type: 'range',
    unit: 'cores',
    default: 0,
    min: 0,
    max: 64,
    step: 0.5,
    mode: 'simple',
    section: 'resources',
    requiresRestart: true,
  },
  {
    key: 'diskQuotaGb',
    scope: 'panel',
    label: 'Disk quota',
    help: 'Soft limit on this server’s folder size, enforced by the panel’s storage indexer (Docker cannot cap bind-mount disk usage). Over quota, disk-growing actions like mod installs and backups are blocked until space is freed.',
    type: 'range',
    unit: 'GB',
    default: 25,
    min: 0,
    max: 2048,
    step: 5,
    mode: 'simple',
    section: 'resources',
  },
  {
    key: 'quotaStrict',
    scope: 'panel',
    label: 'Strict quota mode',
    help: 'When usage exceeds the quota by more than 10%, gracefully stop the server automatically. Protects the host from runaway world or log growth; the stop is recorded in history.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'resources',
  },
];

export = fields;
