'use strict';

// World: save selection, generation, distances, and world-level toggles.

import type { Field } from './types';

const fields: Field[] = [
  {
    key: 'LEVEL',
    scope: 'env',
    label: 'World save name',
    help: 'Name of the world save directory inside the server folder. Change it to switch between saves — the old world stays on disk under its own name.',
    type: 'text',
    default: 'world',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'SEED',
    scope: 'env',
    label: 'World seed',
    help: 'Seed used when generating a new world. Only affects worlds that have not been created yet — it does nothing to an existing world.',
    type: 'text',
    mode: 'simple',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'LEVEL_TYPE',
    scope: 'env',
    label: 'World type',
    help: 'World generator preset used when a new world is created. Pair Superflat with generator settings below to customize the layers.',
    type: 'enum',
    options: [
      { value: 'DEFAULT', label: 'Default', desc: 'Standard terrain generation.' },
      { value: 'FLAT', label: 'Superflat', desc: 'Flat world; customize layers via generator settings.' },
      { value: 'LARGEBIOMES', label: 'Large biomes', desc: 'Same terrain, but each biome is much bigger.' },
      { value: 'AMPLIFIED', label: 'Amplified', desc: 'Extreme mountains; needs a beefy server.' },
    ],
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'GENERATOR_SETTINGS',
    scope: 'env',
    label: 'Generator settings (JSON)',
    help: 'JSON options that customize world generation for certain world types — for Superflat, the layer list and biome. Layers apply bottom-up from Y=-64.',
    type: 'text',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'WORLD',
    scope: 'env',
    label: 'World download URL / path',
    help: 'URL of a zip/tar archive (or a container path) containing an existing world to import. It is only copied in if the world does not already exist — see "Force world copy" to overwrite.',
    type: 'text',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'FORCE_WORLD_COPY',
    scope: 'env',
    label: 'Force world copy',
    help: 'Re-copies the imported world over the existing one on every start. Leaving this on permanently wipes player progress at each restart — enable once to reset, then turn it back off.',
    type: 'boolean',
    default: false,
    mode: 'advanced',
    section: 'world',
    danger: true,
    requiresRestart: true,
  },
  {
    key: 'SPAWN_PROTECTION',
    scope: 'env',
    label: 'Spawn protection radius',
    help: 'Radius in blocks around spawn that only operators can modify. 0 disables protection; the vanilla default is 16.',
    type: 'number',
    min: 0,
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'VIEW_DISTANCE',
    scope: 'env',
    label: 'View distance',
    help: 'How many chunks around each player the server sends to their client (vanilla default 10). One of the biggest levers for RAM, CPU, and bandwidth — lower it if the server lags.',
    type: 'number',
    unit: 'chunks',
    min: 3,
    max: 32,
    mode: 'simple',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'SIMULATION_DISTANCE',
    scope: 'env',
    label: 'Simulation distance',
    help: 'How many chunks around each player actually tick — mobs, crops, machines (vanilla default 10). A big performance lever alongside view distance.',
    type: 'number',
    unit: 'chunks',
    min: 3,
    max: 32,
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'MAX_WORLD_SIZE',
    scope: 'env',
    label: 'World border radius',
    help: 'Maximum world border radius in blocks (vanilla default 29999984). Useful to cap disk usage from exploration.',
    type: 'number',
    unit: 'blocks',
    min: 1,
    max: 29999984,
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'ALLOW_NETHER',
    scope: 'env',
    label: 'Allow the Nether',
    help: 'Whether players can travel to the Nether dimension through portals.',
    type: 'boolean',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'GENERATE_STRUCTURES',
    scope: 'env',
    label: 'Generate structures',
    help: 'Whether villages, strongholds, and other structures generate in new chunks.',
    type: 'boolean',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'SPAWN_ANIMALS',
    scope: 'env',
    label: 'Spawn animals',
    help: 'Whether passive animals spawn naturally. Recent Minecraft versions moved this to a gamerule and no longer read this property.',
    type: 'boolean',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'SPAWN_MONSTERS',
    scope: 'env',
    label: 'Spawn monsters',
    help: 'Whether hostile mobs spawn naturally at night and in the dark.',
    type: 'boolean',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'SPAWN_NPCS',
    scope: 'env',
    label: 'Spawn villagers',
    help: 'Whether villagers spawn. Recent Minecraft versions no longer read this property.',
    type: 'boolean',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
  {
    key: 'HARDCORE',
    scope: 'env',
    label: 'Hardcore mode',
    help: 'On death, players are switched to spectator mode instead of respawning. Difficulty is locked to hard.',
    type: 'boolean',
    mode: 'advanced',
    section: 'world',
    danger: true,
    requiresRestart: true,
  },
  {
    key: 'ENABLE_COMMAND_BLOCK',
    scope: 'env',
    label: 'Enable command blocks',
    help: 'Allows command blocks to run their commands. Required by many adventure maps and some datapacks.',
    type: 'boolean',
    mode: 'advanced',
    section: 'world',
    requiresRestart: true,
  },
];

export = fields;
